feat(level-one): init
atls-academy/brusselboy.github.io pull request #2
Opened 2022-02-14 23:36 UTC by brusselboy

2022-02-15 10:15 UTC, TorinAsakura requested changes

2022-02-15 10:15 UTC, TorinAsakura commented on academy/level-one/index.html
> +                    </p>
1. Что такое баннер? Там есть изображение и изображением оно и должно быть
2. см. выше
3. Зачем тут параграф?

2022-02-15 10:15 UTC, TorinAsakura commented on academy/level-one/index.html
> +            <h1>Процесс обучения</h1>
[Семантика этого заголовка](https://ru.hexlet.io/blog/posts/semantika-zagolovkov-kak-pravilno-strukturirovat-informatsiyu-na-veb-stranitsah)

2022-02-15 10:15 UTC, TorinAsakura commented on academy/level-one/index.html
> +</html>
проверь на предмет "последней строки"

2022-02-15 10:15 UTC, TorinAsakura commented on academy/level-one/styles/index/hero.css
> +}
не нужно привязывать хтмл объекты к контексту дизайна, как минимум, ты уберёшь параграф и...у тебя всё развалится

2022-02-15 15:20 UTC, TorinAsakura requested changes

2022-02-15 15:20 UTC, TorinAsakura commented on academy/level-one/index.html
> +                <svg width="480" height="40" viewBox="0 0 480 40" fill="none" xmlns="http://www.w3.org/2000/svg" class="logo" onclick="location.reload();">
зачем тут onClick? Семантика должна выглядеть примерно так a > div > svg

2022-02-15 15:20 UTC, TorinAsakura commented on academy/level-one/index.html
>          <div class="process-content">
processContent

2022-02-15 15:20 UTC, TorinAsakura commented on academy/level-one/index.html
> +            <h1 class="process-content-title">Процесс обучения</h1>
processContent-title

2022-02-15 15:20 UTC, TorinAsakura commented on academy/level-one/index.html
> +                    <div class="card-image">
для блоков с изображениями нужно задавать бэкграунд-калор в качестве фоллбека

2022-02-15 15:20 UTC, TorinAsakura commented on academy/level-one/index.html
> +                    <h2 class="card-title">Заголовок</h2>
Ещё раз **внимательно** прочти гайд по семантике

2022-02-15 15:20 UTC, TorinAsakura commented on academy/level-one/styles/index/hero.css
> +    margin-left: 12%;
никогда не задавай врапперам и контейнерам отступы в относительных величинах, у тебя есть в дизайне точный размер отступа

2022-02-15 18:34 UTC, TorinAsakura requested changes

2022-02-15 18:34 UTC, TorinAsakura commented on academy/level-one/index.html
> +            <a href="index.html">
что будет когда ты захочешь перейти на главную по твоему линку, скажем, с урла вида localhost/page?id=xxx ?

2022-02-15 18:34 UTC, TorinAsakura commented on academy/level-one/index.html
> +            <a href="index.html">
Где title?

2022-02-15 18:34 UTC, TorinAsakura commented on academy/level-one/index.html
> +                <div class="mobile-logo">
https://tproger.ru/translations/responsive-web-design-tips/

2022-02-16 08:41 UTC, TorinAsakura requested changes

2022-02-16 08:41 UTC, TorinAsakura commented on academy/level-one/index.html
> +      <a href="https://atls.academy/" rel="first" title="Atlantis Academy">
http://htmlbook.ru/html/a/rel

2022-02-16 08:41 UTC, TorinAsakura commented on academy/level-one/index.html
> +      <div class="cards">
плохо подобран нейминг, ты вроде пришёл из process, а тут какие-то cards, если это часть твоего фрагмента то скорее это fragmentEntity-item

2022-02-16 08:41 UTC, TorinAsakura commented on academy/level-one/index.html
>  <div class="process">
что за process? что это? какой процесс? о чём идёт речь? не ленись писать нормальные "дружелюбные" именования, иначе начинаешь путать людей заставляю додумывать их, а это уже, между прочим, один из антипаттернов

2022-02-16 08:41 UTC, TorinAsakura commented on academy/level-one/styles/index/hero.css
> +        float: left;
https://idg.net.ua/blog/uchebnik-css/razmetka-css/verstka-s-float/problemy, подумай насчёт целесообразности флоата тут

2022-02-16 08:41 UTC, TorinAsakura requested changes

2022-02-16 08:41 UTC, TorinAsakura commented on academy/level-one/index.html
> +  <div class="process-wrapper">
зачем тут wrapper?

2022-02-16 08:44 UTC, TorinAsakura commented on academy/level-one/index.html
> +            <a href="index.html">
https://htmlacademy.ru/blog/boost/frontend/links

2022-02-16 09:12 UTC, brusselboy commented on academy/level-one/index.html
> +  <div class="process-wrapper">
> зачем тут wrapper?

process-wrapper это дочерний div, div`a process. Использую его, чтобы сделать отступы внутри родительского div process

2022-02-16 15:07 UTC, TorinAsakura commented on academy/level-one/index.html
> +      <div class="processEducationContent-items">
зачеееееммм????? ну это же тупо обёртка! зачем ты от неё наследуешь нейминги??

2022-02-16 19:20 UTC, TorinAsakura approved these changes

2022-02-16 19:20 UTC, merged